### ISSUE TITLE
Vorgemerkte Umsätze ...

### ISSUE THREAD

**Issue by confluencepoint** [krachtstefan/moneymoney2ynab#1]
Um **vorgemerkte** Umsätze zu exportieren, würde es da genügen folgende Zeile
```
if transaction.booked then
 … 
end
```
auszuschalten?

**Comment by krachtstefan** [comment]
Ganz genau. Auch wenn man eigentlich annehmen würde, dass man gerne alle Transaktionen importieren möchte, habe ich das bewusst ausgestellt. 
Ein OFX-Import in YNAB geht immer davon aus, dass alles schon abgebucht wurde und setzt alle importierten Transaktionen auf cleared. Du musst dann nach jedem import die vorgemerkten Transaktionen per Hand raussuchen und auf uncleared setzen, damit der Kontostand am Ende stimmt. Dadurch hast du viel Handarbeit und der Import spart dir unter Umständen überhaupt keine Zeit ein.

Wenn du das in Kauf nehmen willst und lieber, kannst du den nativen OFX-Export von MoneyMoney nutzen.

**Comment by confluencepoint** [comment]
Ich habe noch einmal darüber nachgedacht. **Das macht Sinn!** 
Dass die Umsätze gleich als „cleared“ gesetzt werden, hatte ich so noch nicht bemerkt. 
Danke für das Feature. Das hat mich bei der Desktop-Variante immer maßlos gestört.

_Ich suche immer noch eine Möglichkeit das alles relativ automatisiert in die Web-Version zu bekommen. Leider sind die Drag&Drop Automatisierungsmöglichkeiten in OS X recht bescheiden._

**Comment by krachtstefan** [comment]
Gerne. Um von diesem Skript zu exportieren nutze ich in MoneyMoney noch zusätzlich einen Keyboardshortcut. Damit geht es relativ fix, wenn auch nicht automatisiert.
