### ISSUE TITLE
Planned Transactions as unchecked

### ISSUE THREAD

**Issue by ghost** [krachtstefan/moneymoney2ynab#3]
Hi! 

I really appreciate moneymoney2ynab. It would be great if planned transaction for ynab would not only excluded but rather imported as unchecked. Is that possible?

Thank you so much!

**Comment by krachtstefan** [comment]
Unfortunately not. As far as I know, the import dialog will always mark all imported items as cleared. Which kind of makes sense to show you the currently imported items and tell them apart from the older ones

**Comment by ghost** [comment]
Ah, i understand. Thanks!
