### ISSUE TITLE
STMTTRN.name too long

### ISSUE THREAD

**Issue by chbndrhnns** [krachtstefan/moneymoney2ynab#4]
The tool I use to process the OFX files complains like this:

```
ValueError: Can't set OFX.bankmsgsrsv1 to <Element 'BANKMSGSRSV1' at 0x104826830>: 
Can't set STMTTRNRS.stmtrs to <Element 'STMTRS' at 0x104826cb0>: 
Can't set STMTRS.banktranlist to <Element 'BANKTRANLIST' at 0x104826e90>: 
Can't set STMTTRN.name to PayPal (Europe) S.a.r.l. et Cie., S.C.A.: 'PayPal (Europe) S.a.r.l. et Cie., S.C.A.' is too long; max length=32
```

Would you be able to fix that?

**Comment by krachtstefan** [comment]
Can you give me a little bit more context to reproduce this error? 

> The tool I use to process the OFX

Which tool do you mean? Shouldn't there just be MoneyMoney and YNAB?

**Comment by chbndrhnns** [comment]
Sure. I parse the OFX files using [ofxtools](https://pypi.org/project/ofxtools/) and then I send them to YNAB using a small Python application. While YNAB seems not to care about OFX specs, ofxtools does. And there is a character limit on the `STMTTRN.name` field

**Comment by krachtstefan** [comment]
I think a 32 character limitation in this plugin would unnecessary cut off some names after the MoneyMoney export which might also lead to breaking existing YNAB matchings. 

So I guess you could either

- fork this repo and implement the name limitation
- add a post processing step to your pipeline which cuts off the name after MoneyMoney export

hope this helps

**Comment by chbndrhnns** [comment]
I understand that and will probably go ahead with a fork. I also agree with your thought that this limit unreasonable.

However, MoneyMoney conforms to OFX here if you export OFX without your plugin. Technically speaking, it's not OFX-compliant what your plugin writes.
